version: '3'
services:
  service:
    hostname: service
    image: service:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=data
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
